# Generated by Django 5.1.4 on 2024-12-19 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField(max_length=150)),
                ('audiences', models.CharField(choices=[('Parents', 'Parents'), ('Teachers', 'Teachers'), ('Students', 'Students'), ('Everyone', 'Everyone')], default='Everyone', max_length=8)),
                ('scheduled_for', models.DateField(default=datetime.datetime.now)),
                ('priority', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=1, verbose_name='priority')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=100)),
                ('event_tags', models.CharField(choices=[('examination', 'Examination'), ('holiday', 'Holiday'), ('meeting', 'Meeting'), ('extracurricular', 'Extracurricular'), ('workshop', 'Workshop'), ('graduation', 'Graduation'), ('festival', 'Festival')], max_length=15)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
