# Generated by Django 5.1.4 on 2024-12-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parents',
        ),
        migrations.AddField(
            model_name='parents',
            name='wards',
            field=models.ManyToManyField(blank=True, to='frontline.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='my_passkey',
            field=models.CharField(default='', max_length=10),
        ),
    ]
