# Generated by Django 5.1.4 on 2025-01-07 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_email', models.EmailField(max_length=255)),
                ('new_email', models.EmailField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(max_length=64)),
                ('last_changed', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_change_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
