# Generated by Django 5.1.4 on 2024-12-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline', '0003_alter_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
