# Generated by Django 5.1.4 on 2025-01-08 03:55

import backline.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backline', '0001_initial'),
        ('frontline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='staff', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('fullname', models.CharField(blank=True, default='', max_length=200)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_active', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('fullname', models.CharField(blank=True, default='', max_length=200)),
                ('my_passkey', models.CharField(blank=True, max_length=10)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.AddField(
            model_name='approvals',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='assessment_records',
            name='academic_year',
            field=models.ForeignKey(default=backline.models.get_active_academic, on_delete=django.db.models.deletion.RESTRICT, to='backline.academic', verbose_name='academic year'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='academic_calendar',
            field=models.ForeignKey(default=backline.models.get_active_academic, on_delete=django.db.models.deletion.RESTRICT, to='backline.academic', verbose_name='calendar'),
        ),
        migrations.AddField(
            model_name='mailchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_change_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parent', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('fullname', models.CharField(blank=True, default='', max_length=200)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('wards', models.ManyToManyField(blank=True, to='backline.student')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backline.student', verbose_name='student'),
        ),
        migrations.AddField(
            model_name='assessment_records',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backline.student', verbose_name='student'),
        ),
        migrations.CreateModel(
            name='SubClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=1, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('supervisors', models.ManyToManyField(blank=True, related_name='supervisors', to='backline.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('Grade', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='backline.subclasses', verbose_name='associated grade')),
            ],
            options={
                'verbose_name_plural': 'student classes',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backline.subclasses', verbose_name='Student class'),
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name of subject')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('classes', models.ManyToManyField(to='backline.subclasses', verbose_name='Classes')),
                ('supervisors', models.ManyToManyField(blank=True, to='backline.staff')),
            ],
            options={
                'verbose_name_plural': 'subjects',
            },
        ),
        migrations.AddField(
            model_name='assessment_records',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backline.subjects', verbose_name='subject'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('date', 'student', 'academic_calendar'), name='unique_attendance_per_student_per_date'),
        ),
        migrations.AddConstraint(
            model_name='assessment_records',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'academic_year'), name='Student Must have a unique assessment subject and academic year'),
        ),
    ]
